name: ML Model CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run model validation tests
      run: |
        echo "Running comprehensive model tests..."
        echo "=================================="
        python -m pytest tests/test_model.py -v
        
    - name: Verify model architecture
      run: |
        echo "\nVerifying model architecture and parameters..."
        echo "==========================================="
        python tests/test_model.py 